[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire        @ ^2.3.8
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Os

monitor_port = /dev/ttyUSB0
upload_port  = /dev/ttyUSB0